version: '3.12'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=rhd_db
      - SECRET_KEY=api
    extra_hosts:
      - "host.docker.internal:host-gateway"